# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

inhibit_all_warnings!


pod 'Masonry'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SSKeychain'
pod 'UMengAnalytics-NO-IDFA'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'DZNEmptyDataSet'
# 二维码
pod 'HMQRCodeScanner'
#显示的控制台打印信息
pod 'GHConsole'


target 'iOSProjects' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSProjects

  target 'iOSProjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSProjectsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
